import type { Metadata } from 'next';
import './globals.css';
import { SessionProvider } from 'next-auth/react';
import ApolloWrapper from '@/lib/ApolloWrapper';
import { Header } from '@/components/header';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <SessionProvider>
                    <ApolloWrapper>
                        <Header />
                        {children}
                    </ApolloWrapper>
                </SessionProvider>
            </body>
        </html>
    );
}
