version: '3.4'

volumes:
  mssql_data:
    name: 'mssql_microservicescafe'
  elasticsearch_data:
    name: 'elasticsearch_microservicescafe'

services:
  rabbitmq:
    ports:
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  mssql:
    environment:
      - SA_PASSWORD=Passw@rd!
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  gateway.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  products.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8082
      - ASPNETCORE_HTTPS_PORTS=8083
      - ConnectionStrings__ProductsDbConnectionString=${PRODUCTS_DB_CONNECTIONSTRING}
      - ConnectionStrings__Elasticsearch=${ELASTICSEARCH_URL}
      - OpenIddict__Issuer=${OPENIDDICT_ISSUER}
      - OpenIddict__EncryptionKey=${OPENIDDICT_ENCRYPTION_KEY}
    ports:
      - "8082:8082"
      - "8083:8083"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    extra_hosts:
      - "localhost:172.17.0.1"

  inventory.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8088
      - ASPNETCORE_HTTPS_PORTS=8089
      - ConnectionStrings__InventoryDbConnectionString=${INVENTORY_DB_CONNECTIONSTRING}
      - OpenIddict__Issuer=${OPENIDDICT_ISSUER}
      - OpenIddict__EncryptionKey=${OPENIDDICT_ENCRYPTION_KEY}
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    ports:
      - "8088:8088"
      - "8089:8089"
    extra_hosts:
      - "localhost:172.17.0.1"
      
  price.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8090
      - ASPNETCORE_HTTPS_PORTS=8091
      - ConnectionStrings__PriceDbConnectionString=${PRICE_DB_CONNECTIONSTRING}
      - OpenIddict__Issuer=${OPENIDDICT_ISSUER}
      - OpenIddict__EncryptionKey=${OPENIDDICT_ENCRYPTION_KEY}
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    ports:
      - "8090:8090"
      - "8091:8091"
    extra_hosts:
      - "localhost:172.17.0.1"

  auth.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8084
      - ASPNETCORE_HTTPS_PORTS=8085
      - ConnectionStrings__DbConnection=${AUTH_DB_CONNECTIONSTRING}
      - OpenIddict__Issuer=${OPENIDDICT_ISSUER}
      - OpenIddict__EncryptionKey=${OPENIDDICT_ENCRYPTION_KEY}
    ports:
      - "8084:8084"
      - "8085:8085"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  user.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8086
      - ASPNETCORE_HTTPS_PORTS=8087
      - OpenIddict__Issuer=${OPENIDDICT_ISSUER}
      - OpenIddict__EncryptionKey=${OPENIDDICT_ENCRYPTION_KEY}
    ports:
      - "8086:8086"
      - "8087:8087"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    extra_hosts:
      - "localhost:172.17.0.1"

  elasticsearch:
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
