import './globals.css';
import { notFound } from 'next/navigation';
import { SessionProvider } from 'next-auth/react';
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { NuqsAdapter } from 'nuqs/adapters/next/app';

import Footer from '@/components/common/footer';
import { Header } from '@/components/common/header';
import { ThemeProvider } from '@/components/common/theme-provider';
import { routing } from '@/i18n/routing';
import ApolloWrapper from '@/lib/ApolloWrapper';

import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const RootLayout = async ({
    children,
    params,
}: Readonly<{
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}>) => {
    const { locale } = await params;
    if (!hasLocale(routing.locales, locale)) {
        notFound();
    }

    return (
        <html lang={locale} suppressHydrationWarning>
            <body className="min-h-screen flex flex-col">
                <NextIntlClientProvider>
                    <SessionProvider>
                        <NuqsAdapter>
                            <ApolloWrapper>
                                <ThemeProvider
                                    attribute="class"
                                    defaultTheme="light"
                                    enableSystem
                                    disableTransitionOnChange
                                >
                                    <Header />
                                    <main className="flex-1">{children}</main>
                                    <Footer />
                                </ThemeProvider>
                            </ApolloWrapper>
                        </NuqsAdapter>
                    </SessionProvider>
                </NextIntlClientProvider>
            </body>
        </html>
    );
};

export default RootLayout;
