import './globals.css';
import { notFound } from 'next/navigation';
import { SessionProvider } from 'next-auth/react';
import { NextIntlClientProvider, hasLocale } from 'next-intl';

import { routing } from '@/i18n/routing';
import ApolloWrapper from '@/lib/ApolloWrapper';

import Footer from './components/footer';
import { Header } from './components/header';

import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const RootLayout = async ({
    children,
    params,
}: Readonly<{
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}>) => {
    const { locale } = await params;
    if (!hasLocale(routing.locales, locale)) {
        notFound();
    }

    return (
        <html lang={locale}>
            <body>
                <NextIntlClientProvider>
                    <SessionProvider>
                        <ApolloWrapper>
                            <Header />
                            {children}
                            <Footer />
                        </ApolloWrapper>
                    </SessionProvider>
                </NextIntlClientProvider>
            </body>
        </html>
    );
};

export default RootLayout;
