version: '3.4'
name: microservices_cafe

networks:
    microservicescafe_net:
        driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
        - microservicescafe_net

  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    networks:
        - microservicescafe_net

  microservicescafe.gateway.api:
    container_name: gateway_api
    image: ${DOCKER_REGISTRY-}microservicescafegatewayapi
    build:
        context: ../..
        dockerfile: src/Gateway/MicroservicesCafe.Gateway.API/Dockerfile  
    networks:
        - microservicescafe_net
    depends_on:
        - mssql

  microservicescafe.products.api:
    container_name: products_api
    image: ${DOCKER_REGISTRY-}microservicescafeproductsapi
    build:
      context: ../..
      dockerfile: src/Microservices/Products/MicroservicesCafe.Products.API/Dockerfile
    networks:
        - microservicescafe_net
    depends_on:
        - mssql

  auth.server:
    container_name: auth_server
    image: ${DOCKER_REGISTRY-}authserver
    build:
      context: ../..
      dockerfile: src/Auth/Auth.Server/Dockerfile
    networks:
        - microservicescafe_net
    depends_on:
        - mssql
