version: '3.4'
name: microservices_cafe

networks:
    rabbitmq_net:
        driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
        - rabbitmq_net

  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    networks:
        - rabbitmq_net

  microservicescafe.gateway.api:
    container_name: gateway_api
    image: ${DOCKER_REGISTRY-}microservicescafegatewayapi
    build:
        context: ../..
        dockerfile: src/Gateway/MicroservicesCafe.Gateway.API/Dockerfile  
    networks:
        - rabbitmq_net
    depends_on:
        - mssql

  microservicescafe.product.api:
    container_name: product_api
    image: ${DOCKER_REGISTRY-}microservicescafeproductapi
    build:
      context: ../..
      dockerfile: src/Microservices/Product/MicroservicesCafe.Product.API/Dockerfile
    networks:
        - rabbitmq_net
    depends_on:
        - mssql
        
